// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsvKT0GzG29uB7J407_cwaL5LgJCGOTLo',
    appId: '1:803309783192:web:d8ee74b204d16987b6e8ed',
    messagingSenderId: '803309783192',
    projectId: 'bio-app-99e34',
    authDomain: 'bio-app-99e34.firebaseapp.com',
    storageBucket: 'bio-app-99e34.firebasestorage.app',
    measurementId: 'G-R1DCQD4SEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGLuIi05xqesVcuI8wctLm90qKaitYsjw',
    appId: '1:803309783192:android:c287a3e48bae0b29b6e8ed',
    messagingSenderId: '803309783192',
    projectId: 'bio-app-99e34',
    storageBucket: 'bio-app-99e34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFLTeWq9OE_Z1aJbpaUfj7-MFvG_i36pY',
    appId: '1:803309783192:ios:bb1f434fe59392beb6e8ed',
    messagingSenderId: '803309783192',
    projectId: 'bio-app-99e34',
    storageBucket: 'bio-app-99e34.firebasestorage.app',
    iosBundleId: 'com.example.biocode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFLTeWq9OE_Z1aJbpaUfj7-MFvG_i36pY',
    appId: '1:803309783192:ios:bb1f434fe59392beb6e8ed',
    messagingSenderId: '803309783192',
    projectId: 'bio-app-99e34',
    storageBucket: 'bio-app-99e34.firebasestorage.app',
    iosBundleId: 'com.example.biocode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsvKT0GzG29uB7J407_cwaL5LgJCGOTLo',
    appId: '1:803309783192:web:dac21a2a72678eacb6e8ed',
    messagingSenderId: '803309783192',
    projectId: 'bio-app-99e34',
    authDomain: 'bio-app-99e34.firebaseapp.com',
    storageBucket: 'bio-app-99e34.firebasestorage.app',
    measurementId: 'G-2M7T6DEFPZ',
  );
}
